#!/bin/bash

script_root="$(dirname "$0")"
source $script_root/env.sh


#MODEL_FLAGS="--image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16"
#DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule cosine --rescale_learned_sigmas False --rescale_timesteps False --use_scale_shift_norm False"

# Override logdir
#MODEL_PATH=$OPENAI_LOGDIR
#export OPENAI_LOGDIR="output/custom"

export RANK=0
export MASTER_ADDR=127.0.0.1
export MASTER_PORT=29400
export WORLD_SIZE=1

python scripts/image_sample.py --model_path $OPENAI_LOGDIR --num_samples 48 $MODEL_FLAGS $DIFFUSION_FLAGS
